### ISSUE TITLE
Issue with being unable to place blocks in water. (Version 1.1.1 and 1.1.2)

### ISSUE THREAD

**Issue by ProfessorPasta** [infernalstudios/Ocean-Worlds#3]
**Howdy, hope you are having a lovely day!**
Wanted to let you know of an issue I found in case the mod ends up being updated down the road, or ends up being used in other projects! Haven't really written out any detailed bug reports yet, so here we go!

- I noticed that the mod does not allow you to place blocks underwater, and when using a bucket underwater the air pocket left behind does not fill with water. (See image below.)
- You can still break blocks underwater, but they won't fill in with water. (Second image.)
- Water created by the player acts normally, only naturally generated water that is found in bodies of water such as rivers and oceans seems affected.
- Fish and water mobs don't seem to have their pathfinding affected, mob spawns in water seems unaffected.
- Breaking Kelp and Sea Grass creates water that works normally, but only in the space it previously occupied.

I have tested version 1.1.1 and 1.1.2 of the mod, both appear to have this issue.
I am using the Curseforge mod-loader, am in Minecraft 1.20.1, and am using the forge version: 47.3.0 Testing was done with no other mods loader.
_(The 1.19.2 version of the mod does not appear to have this bug, placing blocks works properly in previous builds.)_

I have no experience in coding mods for Minecraft or know much technical about Minecraft, but my guess is that the water source blocks the mod is placing aren't the same ones that are generated in Vanilla. They seem to act more like a full block than typical water, maybe something in Minecraft's code changed from 1.19.2 to 1.20.x which caused this issue?

Love the mod! Hope this is helpful to you!

**Trying to use a bucket underwater:**
![2024-10-25_10 38 35](https://github.com/user-attachments/assets/95c32578-2486-4df3-879d-1d05588ee1e7)
**Behavior when breaking blocks:**
![2024-10-25_10 42 31](https://github.com/user-attachments/assets/20c44f79-80d0-4b10-8575-ef002ef6e793)

**Comment by SwanX1** [comment]
> This is intended, so that the "waves" generated don't flow. The generated water uses a mimicked water, which does not flow.
Without it, the waves would not exist, as well as there would be so many block updates, you could say your last words to your computer, because it would fly up into the sky because of the fans being overloaded, because your CPU would not even have the chance to think about cooling itself down, because it would be too busy thinking about where the water should flow.
Hope this answers your question! :)

_Originally posted by @SwanX1 in https://github.com/infernalstudios/Ocean-Worlds/issues/1#issuecomment-2372273419_
